/*def minSdkVersion = 16

if(cdvMinSdkVersion == null) {
    ext.cdvMinSdkVersion = minSdkVersion;
} else if (cdvMinSdkVersion.toInteger() < minSdkVersion) {
    ext.cdvMinSdkVersion = minSdkVersion;
}*/

repositories{
    google()
    mavenCentral()
    jcenter()
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    implementation 'com.android.support:support-v4:+'
    implementation(name:'barcodescanner', ext:'aar')
    //implementation 'com.google.android.gms:play-services-code-scanner:16.1.0'
}

android {
    packagingOptions {
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
    }
}